[profile.default]
src             = 'src'
out             = 'out'
libs            = ['lib']
optimizer       = true
optimizer_runs  = 200
fs_permissions  = [{ access = "read", path = "./"}]
solc_version    = "0.8.33"
remappings      = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "permit2/=lib/permit2/src/",
    "forge-std/=lib/forge-std/src/"
]

[fuzz]
runs = 500

[invariant]
runs  = 8
depth = 8

[profile.shallow.fuzz]
runs = 250

[profile.deep.fuzz]
runs = 800

[profile.deep.invariant]
runs  = 12
depth = 12

[profile.super_deep.fuzz]
runs = 1500

[profile.super_deep.invariant]
runs  = 16
depth = 16
